[package]
name = "safers"
description = "A client for syspass implemented in Rust"
version = "0.1.0"
authors = ["Martin GUILLOUX <martin.guilloux@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
serde_json = "1.0"
jsonrpc-core = "14.0.5"
reqwest = "0.9.22"
serde_derive = "1.0"
json = "0.12.0"
serde="1.0"
syspass_api= "0.1.4"
users = "0.9"
